name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest
    name: Native Strawberry Perl on Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Strawberry Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: "strawberry"
          perl-version: "5.36"

      - name: Verify Perl version
        run: perl -V

      - name: Install dependencies
        run: cpanm --skip-satisfied --quiet --notest Win32::API~0.77 Win32::Console~0.10 Test::More~0 Encode~0 Exporter~0 Hash::Util~0 Win32~0.44 Win32API::File~0.08 version~0.77

      - name: Run tests
        run: |
          perl Makefile.PL
          gmake test
